version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

    environment:
      url: jdbc:postgresql://THoVTXWjWrw6AiElJGUCemiYDdSASgfO@dpg-cnumn5ljm4es73a074jg-a.oregon-postgres.render.com/classic_yzjm
      dbusername: root
      dbpassword: THoVTXWjWrw6AiElJGUCemiYDdSASgfO 
      driver: org.postgresql.Driver
      spring.jpa.hibernate.ddl-auto: "update"
      spring.thymeleaf.prefix: classpath:/templates/
      spring.thymeleaf.suffix: .html
  
  db:
    image: postgres:latest
    restart: always
    environment:
      M POSTGRES_DB: classic
      POSTGRES_USER: root
      POSTGRES_PASSWORD: THoVTXWjWrw6AiElJGUCemiYDdSASgfO
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8081:80"

volumes:
  postgres-data:

